### ISSUE TITLE
Display summary, score and feedback in a post analysis page

### ISSUE THREAD

**Issue by KenjiPcx** [KenjiPcx/feynman-agent#24]

**Comment by thatjosh** [comment]
WIP: 
<img width="963" alt="image" src="https://github.com/KenjiPcx/feynman-agent/assets/74296152/650f6c84-7c7f-402d-b9d2-9c03f6220ac0">


To do:

* Session data renders hard coded data `(from mockPostSessionAnalysis.ts)` on error, which will be removed once in production. The code to be modified is highlighted with "TODO"
